window.Pakistani_Isolates = [
  {
    "Strain": 22.0322,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5291557,
    "N50": 177225,
    "Contigs": 101,
    "GC_Content": 50.5,
    "CDS": 5221,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "120x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923014",
    "Assembly_Accession": "GCA_024395275.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0323,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5212522,
    "N50": 222065,
    "Contigs": 110,
    "GC_Content": 50.5,
    "CDS": 5041,
    "MLST": "ST73",
    "Phylogroup": "B2",
    "Serovar": "O6:H1",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "104x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923015",
    "Assembly_Accession": "GCA_024395415.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0324,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5156718,
    "N50": 148699,
    "Contigs": 105,
    "GC_Content": 51,
    "CDS": 5065,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "100x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923016",
    "Assembly_Accession": "GCA_024395435.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0325,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5044452,
    "N50": 104610,
    "Contigs": 132,
    "GC_Content": 51,
    "CDS": 4943,
    "MLST": "ST678",
    "Phylogroup": "B1",
    "Serovar": "O104:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "88x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923017",
    "Assembly_Accession": "GCA_024395455.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000180843.3",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0326,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5351403,
    "N50": 214909,
    "Contigs": 99,
    "GC_Content": 50.5,
    "CDS": 5235,
    "MLST": "ST69",
    "Phylogroup": "D",
    "Serovar": "O15:H18",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "104x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923018",
    "Assembly_Accession": "GCA_024395475.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0327,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5423287,
    "N50": 219070,
    "Contigs": 156,
    "GC_Content": 50.5,
    "CDS": 5332,
    "MLST": "ST69",
    "Phylogroup": "D",
    "Serovar": "O15:H18",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "76x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923019",
    "Assembly_Accession": "GCA_024395635.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0328,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5270202,
    "N50": 153084,
    "Contigs": 130,
    "GC_Content": 50.5,
    "CDS": 5181,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "68x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923020",
    "Assembly_Accession": "GCA_024395515.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0329,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4760540,
    "N50": 148405,
    "Contigs": 99,
    "GC_Content": 51,
    "CDS": 4620,
    "MLST": "ST10",
    "Phylogroup": "A",
    "Serovar": "O9:H9",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "163x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923021",
    "Assembly_Accession": "GCA_024395535.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114318.1",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.033,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5352892,
    "N50": 221908,
    "Contigs": 113,
    "GC_Content": 50.5,
    "CDS": 5222,
    "MLST": "ST69",
    "Phylogroup": "D",
    "Serovar": "O15:H18",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "73x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923022",
    "Assembly_Accession": "GCA_024395495.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114317.7",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0331,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5140065,
    "N50": 74718,
    "Contigs": 210,
    "GC_Content": 50.5,
    "CDS": 5165,
    "MLST": "ST10",
    "Phylogroup": "A",
    "Serovar": "O48:H32",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "46x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923023",
    "Assembly_Accession": "GCA_024395315.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0332,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5282152,
    "N50": 214645,
    "Contigs": 85,
    "GC_Content": 50.5,
    "CDS": 5192,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "109x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923024",
    "Assembly_Accession": "GCA_024395295.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0333,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4777255,
    "N50": 171628,
    "Contigs": 66,
    "GC_Content": 50.5,
    "CDS": 4630,
    "MLST": "ST1147",
    "Phylogroup": "B2",
    "Serovar": "O128:H35",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "132x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923025",
    "Assembly_Accession": "GCA_024395335.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0334,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5273466,
    "N50": 134126,
    "Contigs": 154,
    "GC_Content": 50.5,
    "CDS": 5302,
    "MLST": "ST410",
    "Phylogroup": "C",
    "Serovar": "O132:H9",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "71x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923026",
    "Assembly_Accession": "GCA_024395615.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114316.1",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0335,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4975493,
    "N50": 219274,
    "Contigs": 79,
    "GC_Content": 51,
    "CDS": 4831,
    "MLST": "ST156",
    "Phylogroup": "B1",
    "Serovar": "O100/O154:H28",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "112x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923027",
    "Assembly_Accession": "GCA_024395355.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114315.2",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0336,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4981626,
    "N50": 219796,
    "Contigs": 75,
    "GC_Content": 51,
    "CDS": 4834,
    "MLST": "ST156",
    "Phylogroup": "B1",
    "Serovar": "O100/O154:H28",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "97x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923028",
    "Assembly_Accession": "GCA_024395375.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114315.2",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 22.0337,
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5286027,
    "N50": 173687,
    "Contigs": 90,
    "GC_Content": 50.5,
    "CDS": 5203,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "60x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN29923029",
    "Assembly_Accession": "GCA_024395395.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": 55989,
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4989876,
    "N50": 211807,
    "Contigs": 47,
    "GC_Content": 50.786613,
    "CDS": 4966,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196158",
    "Assembly_Accession": "GCA_003028695.1",
    "Genbank_Accession": "CP028304",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000153659.1",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "01_ST405",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5202454,
    "N50": 144053,
    "Contigs": 110,
    "GC_Content": 50.5,
    "CDS": 5179,
    "MLST": "ST405",
    "Phylogroup": "D",
    "Serovar": "O102:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804029",
    "Assembly_Accession": "GCA_049537715.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000211884.2",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "06_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5359055,
    "N50": 197515,
    "Contigs": 132,
    "GC_Content": 50.5,
    "CDS": 5440,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804030",
    "Assembly_Accession": "GCA_049537675.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "11_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5326642,
    "N50": 191062,
    "Contigs": 136,
    "GC_Content": 50.5,
    "CDS": 5386,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804020",
    "Assembly_Accession": "GCA_049538135.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000226050.1",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "12_ST405",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5485357,
    "N50": 147063,
    "Contigs": 131,
    "GC_Content": 50.5,
    "CDS": 5519,
    "MLST": "ST405",
    "Phylogroup": "D",
    "Serovar": "O102:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804025",
    "Assembly_Accession": "GCA_049537635.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "14_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5281928,
    "N50": 188644,
    "Contigs": 139,
    "GC_Content": 50.5,
    "CDS": 5404,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804033",
    "Assembly_Accession": "GCA_049538035.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "15_ST648",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5253887,
    "N50": 169568,
    "Contigs": 143,
    "GC_Content": 50.5,
    "CDS": 5281,
    "MLST": "ST648",
    "Phylogroup": "F",
    "Serovar": "O153:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804031",
    "Assembly_Accession": "GCA_049537695.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "157_ST10",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 4935202,
    "N50": 126451,
    "Contigs": 137,
    "GC_Content": 50.5,
    "CDS": 4971,
    "MLST": "ST617",
    "Phylogroup": "A",
    "Serovar": "-:H9",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804039",
    "Assembly_Accession": "GCA_049537955.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "16_ST162",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 4985581,
    "N50": 163510,
    "Contigs": 110,
    "GC_Content": 50.5,
    "CDS": 4963,
    "MLST": "ST162",
    "Phylogroup": "B1",
    "Serovar": "O88:H10",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804037",
    "Assembly_Accession": "GCA_049537735.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000226053.1",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "175_ST405",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5200177,
    "N50": 145814,
    "Contigs": 119,
    "GC_Content": 50.5,
    "CDS": 5179,
    "MLST": "ST405",
    "Phylogroup": "D",
    "Serovar": "O102:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804036",
    "Assembly_Accession": "GCA_049538055.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000211884.2",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "21_ST162",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 4984737,
    "N50": 165062,
    "Contigs": 110,
    "GC_Content": 50.5,
    "CDS": 4965,
    "MLST": "ST62",
    "Phylogroup": "B1",
    "Serovar": "O88:H10",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804027",
    "Assembly_Accession": "GCA_049537835.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000226053.1",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "31_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5334668,
    "N50": 199986,
    "Contigs": 143,
    "GC_Content": 50.5,
    "CDS": 5319,
    "MLST": "ST38",
    "Phylogroup": "D",
    "Serovar": "O1:H15",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804022",
    "Assembly_Accession": "GCA_049537615.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043001.3",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "38_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5489585,
    "N50": 187284,
    "Contigs": 144,
    "GC_Content": 50.5,
    "CDS": 5627,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804035",
    "Assembly_Accession": "GCA_049538015.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000226579.1",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "44_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5397359,
    "N50": 191062,
    "Contigs": 140,
    "GC_Content": 50.5,
    "CDS": 5505,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804028",
    "Assembly_Accession": "GCA_049538075.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000118492.3",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "51_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5486538,
    "N50": 197842,
    "Contigs": 143,
    "GC_Content": 50.5,
    "CDS": 5617,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804032",
    "Assembly_Accession": "GCA_049706195.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000226579.1",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "59_ST38",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5334598,
    "N50": 222568,
    "Contigs": 118,
    "GC_Content": 50.5,
    "CDS": 5416,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804021",
    "Assembly_Accession": "GCA_049537655.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "81_ST10",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5282394,
    "N50": 119457,
    "Contigs": 193,
    "GC_Content": 50.5,
    "CDS": 5343,
    "MLST": "ST10",
    "Phylogroup": "A",
    "Serovar": "O15:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804034",
    "Assembly_Accession": "GCA_049538115.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "82_ST405",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5283034,
    "N50": 119947,
    "Contigs": 149,
    "GC_Content": 50.5,
    "CDS": 5282,
    "MLST": "ST405",
    "Phylogroup": "D",
    "Serovar": "O102:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804026",
    "Assembly_Accession": "GCA_049537875.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "85_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5364502,
    "N50": 222420,
    "Contigs": 123,
    "GC_Content": 50.5,
    "CDS": 5446,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804038",
    "Assembly_Accession": "GCA_049537755.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "87_ST131",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5148939,
    "N50": 212315,
    "Contigs": 99,
    "GC_Content": 50.5,
    "CDS": 5155,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804023",
    "Assembly_Accession": "GCA_049537845.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "98_ST405",
    "Host": "Homo sapiens",
    "Collection_date": 2014,
    "Length": 5381810,
    "N50": 171413,
    "Contigs": 156,
    "GC_Content": 50.5,
    "CDS": 5398,
    "MLST": "ST405",
    "Phylogroup": "D",
    "Serovar": "O102:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA1247109",
    "BioSample_Accession": "SAMN47804024",
    "Assembly_Accession": "GCA_049537915.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.11",
    "Location": "Pakistan: Isalambad",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Ihsan Ali, Hazara University"
  },
  {
    "Strain": "APEC 01",
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4609982,
    "N50": 106447,
    "Contigs": 68,
    "GC_Content": 50.83303,
    "CDS": 4500,
    "MLST": "ST167",
    "Phylogroup": "A",
    "Serovar": "-:H9",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196152",
    "Assembly_Accession": "GCA_003028815.1",
    "Genbank_Accession": "CP028310",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000121695.1",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "B2",
    "Host": "Homo sapiens",
    "Collection_date": "10/30/2017",
    "Length": 5075880,
    "N50": 55487,
    "Contigs": 407,
    "GC_Content": 50.69986,
    "CDS": 5360,
    "MLST": "ST44",
    "Phylogroup": "A",
    "Serovar": "-:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA630338",
    "BioSample_Accession": "SAMN14832660",
    "Assembly_Accession": "GCA_013240345.1",
    "Genbank_Accession": "JABFHH000000000",
    "Method": "Newbler v. 3.0",
    "Location": "Pakistan",
    "Isolation_source": "Vaginal swab",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": ""
  },
  {
    "Strain": "CFT073",
    "Host": "Homo sapiens",
    "Collection_date": "",
    "Length": 5231428,
    "N50": 5231428,
    "Contigs": 1,
    "GC_Content": 50.5,
    "CDS": 5589,
    "MLST": "ST73",
    "Phylogroup": "B2",
    "Serovar": "O6:H1",
    "Host_disease": "Urinary tract infection",
    "Level": "Complete Genome",
    "Platform": "",
    "Genome_Coverage": "1x",
    "BioProject_Accession": "PRJNA313",
    "BioSample_Accession": "SAMN02604094",
    "Assembly_Accession": "GCA_000007445.1",
    "Genbank_Accession": "AE014075",
    "Method": "",
    "Location": "USA: Maryland",
    "Isolation_source": "",
    "Isolation_type": "",
    "SNP_cluster": "",
    "Additional_Metadata": "University of Wisconsin-Madison, USA"
  },
  {
    "Strain": "CFT073",
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4721099,
    "N50": 88381,
    "Contigs": 94,
    "GC_Content": 50.760834,
    "CDS": 4615,
    "MLST": "ST453",
    "Phylogroup": "B1",
    "Serovar": "O23:H16",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196153",
    "Assembly_Accession": "GCA_003028795.1",
    "Genbank_Accession": "CP028309",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043352.2",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "CUI-B1",
    "Host": "Homo sapiens",
    "Collection_date": "10/5/2021",
    "Length": 5458596,
    "N50": 5112135,
    "Contigs": 12,
    "GC_Content": 50.402027,
    "CDS": 6007,
    "MLST": "ST648",
    "Phylogroup": "F",
    "Serovar": "O1:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "170.0x",
    "BioProject_Accession": "PRJNA956226",
    "BioSample_Accession": "SAMN34205701",
    "Assembly_Accession": "",
    "Genbank_Accession": "JARWMK000000000",
    "Method": "Geneious Prime v. 2023.1",
    "Location": "Pakistan",
    "Isolation_source": "Urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": ""
  },
  {
    "Strain": "E24377A",
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4721864,
    "N50": 88381,
    "Contigs": 97,
    "GC_Content": 50.736443,
    "CDS": 4636,
    "MLST": "ST453",
    "Phylogroup": "B1",
    "Serovar": "O23:H16",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196154",
    "Assembly_Accession": "GCA_003028775.1",
    "Genbank_Accession": "CP028308",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043352.2",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "EC1O25b:H4/ST131",
    "Host": "Homo sapiens",
    "Collection_date": "6/5/2020",
    "Length": 5228545,
    "N50": 145838,
    "Contigs": 275,
    "GC_Content": 50.676277,
    "CDS": 5488,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary Tract Infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "250.0x",
    "BioProject_Accession": "PRJNA1002788",
    "BioSample_Accession": "SAMN36861360",
    "Assembly_Accession": "",
    "Genbank_Accession": "JAUZWA000000000",
    "Method": "SPAdes v. PATRIC",
    "Location": "Pakistan",
    "Isolation_source": "Urine sample",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": ""
  },
  {
    "Strain": "EDL933",
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4709911,
    "N50": 88381,
    "Contigs": 94,
    "GC_Content": 50.763325,
    "CDS": 4635,
    "MLST": "ST453",
    "Phylogroup": "B1",
    "Serovar": "O23:H16",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196157",
    "Assembly_Accession": "GCA_003028715.1",
    "Genbank_Accession": "CP028305",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043352.2",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "EQ101",
    "Host": "Homo sapiens",
    "Collection_date": "2/15/2020",
    "Length": 5733813,
    "N50": 13672,
    "Contigs": 738,
    "GC_Content": 50.84226,
    "CDS": 6229,
    "MLST": "ST1193",
    "Phylogroup": "B2",
    "Serovar": "-:H5",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "71.0x",
    "BioProject_Accession": "PRJNA814894",
    "BioSample_Accession": "SAMN26578128",
    "Assembly_Accession": "GCA_022604675.1",
    "Genbank_Accession": "JALAIU000000000",
    "Method": "SPAdes v. 3.15.2",
    "Location": "Pakistan",
    "Isolation_source": "clinical sample",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Sareen Khan"
  },
  {
    "Strain": "MG655",
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4736591,
    "N50": 88381,
    "Contigs": 97,
    "GC_Content": 50.777607,
    "CDS": 4665,
    "MLST": "ST453",
    "Phylogroup": "B1",
    "Serovar": "O23:H16",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196156",
    "Assembly_Accession": "GCA_003028735.1",
    "Genbank_Accession": "CP028306",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043352.2",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "PK5074",
    "Host": "Homo sapiens",
    "Collection_date": "12/17/2019",
    "Length": 5321746,
    "N50": 4781220,
    "Contigs": 6,
    "GC_Content": 50.53351,
    "CDS": 5422,
    "MLST": "ST48",
    "Phylogroup": "A",
    "Serovar": "-:H11",
    "Host_disease": "Urinary Tract Infection",
    "Level": "Complete Genome",
    "Platform": "Illumina HiSeq; Oxford Nanopore MinION",
    "Genome_Coverage": "100x",
    "BioProject_Accession": "PRJNA719724",
    "BioSample_Accession": "SAMN18615003",
    "Assembly_Accession": "GCA_017903455.1",
    "Genbank_Accession": "CP072802,CP072805,CP072804,CP072806,CP072803,CP072807",
    "Method": "Unicycler v. 0.4.4",
    "Location": "Pakistan: Faisalabad",
    "Isolation_source": "Urine sample",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000094180.1",
    "Additional_Metadata": "Dr. Mashkoor"
  },
  {
    "Strain": "PSU-5252",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4499739,
    "N50": 99768,
    "Contigs": 138,
    "GC_Content": 51,
    "CDS": 4388,
    "MLST": "ST871",
    "Phylogroup": "A",
    "Serovar": "O19:H19",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "141x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614555",
    "Assembly_Accession": "GCA_023019465.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000108590.2",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5253",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4736757,
    "N50": 131968,
    "Contigs": 104,
    "GC_Content": 51,
    "CDS": 4600,
    "MLST": "ST10",
    "Phylogroup": "A",
    "Serovar": "O9:H9",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "57x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614556",
    "Assembly_Accession": "GCA_023018845.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114318.1",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5254",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5370962,
    "N50": 191981,
    "Contigs": 94,
    "GC_Content": 50.5,
    "CDS": 5304,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "91x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614557",
    "Assembly_Accession": "GCA_023019485.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5255",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 4988622,
    "N50": 94792,
    "Contigs": 142,
    "GC_Content": 51,
    "CDS": 4920,
    "MLST": "ST10",
    "Phylogroup": "A",
    "Serovar": "-:H10",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "93x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614558",
    "Assembly_Accession": "GCA_023019125.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000108331.1",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5256",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5001620,
    "N50": 119096,
    "Contigs": 138,
    "GC_Content": 51,
    "CDS": 4939,
    "MLST": "ST10",
    "Phylogroup": "A",
    "Serovar": "-:H10",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "67x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614559",
    "Assembly_Accession": "GCA_023019105.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000108331.1",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5257",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5248880,
    "N50": 139499,
    "Contigs": 126,
    "GC_Content": 50.5,
    "CDS": 5119,
    "MLST": "ST7401",
    "Phylogroup": "D",
    "Serovar": "O15:H18",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "107x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614560",
    "Assembly_Accession": "GCA_023465455.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5258",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5191637,
    "N50": 108305,
    "Contigs": 190,
    "GC_Content": 50.5,
    "CDS": 5237,
    "MLST": "ST452",
    "Phylogroup": "B2",
    "Serovar": "-:H27",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "135x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614561",
    "Assembly_Accession": "GCA_023019145.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5259",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5343231,
    "N50": 158933,
    "Contigs": 119,
    "GC_Content": 50.5,
    "CDS": 5288,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "93x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614562",
    "Assembly_Accession": "GCA_023019165.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000130419.1",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5260",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5020244,
    "N50": 119017,
    "Contigs": 158,
    "GC_Content": 50.5,
    "CDS": 4985,
    "MLST": "ST617",
    "Phylogroup": "A",
    "Serovar": "-:H10",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "176x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614563",
    "Assembly_Accession": "GCA_023019185.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5261",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5217943,
    "N50": 209933,
    "Contigs": 77,
    "GC_Content": 50.5,
    "CDS": 5070,
    "MLST": "ST648",
    "Phylogroup": "F",
    "Serovar": "O153:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "84x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614564",
    "Assembly_Accession": "GCA_023019205.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5262",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5442617,
    "N50": 176398,
    "Contigs": 130,
    "GC_Content": 50.5,
    "CDS": 5327,
    "MLST": "ST648",
    "Phylogroup": "F",
    "Serovar": "O153:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "74x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614565",
    "Assembly_Accession": "GCA_023019225.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5263",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5343881,
    "N50": 163456,
    "Contigs": 151,
    "GC_Content": 50.5,
    "CDS": 5218,
    "MLST": "ST648",
    "Phylogroup": "F",
    "Serovar": "O1:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "86x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614566",
    "Assembly_Accession": "GCA_023019245.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5264",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5361453,
    "N50": 186354,
    "Contigs": 122,
    "GC_Content": 50.5,
    "CDS": 5226,
    "MLST": "ST69",
    "Phylogroup": "D",
    "Serovar": "O15:H18",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "115x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27998150",
    "Assembly_Accession": "GCA_023203875.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000114317.7",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5265",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5311178,
    "N50": 191623,
    "Contigs": 102,
    "GC_Content": 51,
    "CDS": 5262,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "95x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614567",
    "Assembly_Accession": "GCA_023019285.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000108330.5",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5266",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5287678,
    "N50": 169760,
    "Contigs": 131,
    "GC_Content": 51,
    "CDS": 5236,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "45x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614568",
    "Assembly_Accession": "GCA_023019305.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000108330.5",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5267",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5157367,
    "N50": 137022,
    "Contigs": 148,
    "GC_Content": 50.5,
    "CDS": 5109,
    "MLST": "ST648",
    "Phylogroup": "F",
    "Serovar": "O8:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "59x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614569",
    "Assembly_Accession": "GCA_023019265.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5268",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5291270,
    "N50": 81850,
    "Contigs": 168,
    "GC_Content": 50.5,
    "CDS": 5106,
    "MLST": "ST452",
    "Phylogroup": "D",
    "Serovar": "O102:H6",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "150x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614570",
    "Assembly_Accession": "GCA_023019345.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "PSU-5269",
    "Host": "Homo sapiens",
    "Collection_date": 2021,
    "Length": 5359521,
    "N50": 180835,
    "Contigs": 125,
    "GC_Content": 50.5,
    "CDS": 5312,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "ILLUMINA",
    "Genome_Coverage": "76x",
    "BioProject_Accession": "PRJNA357722",
    "BioSample_Accession": "SAMN27614571",
    "Assembly_Accession": "GCA_023019365.1",
    "Genbank_Accession": "",
    "Method": "SKESA v. 2.2",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000109486.17",
    "Additional_Metadata": "National University of Sciences & Technology"
  },
  {
    "Strain": "Sakai",
    "Host": "Homo sapiens",
    "Collection_date": "12/6/2016",
    "Length": 4709905,
    "N50": 88381,
    "Contigs": 94,
    "GC_Content": 50.763325,
    "CDS": 4637,
    "MLST": "ST453",
    "Phylogroup": "B1",
    "Serovar": "O23:H16",
    "Host_disease": "Urinary tract infection",
    "Level": "Chromosome",
    "Platform": "Illumina MiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA389368",
    "BioSample_Accession": "SAMN07196155",
    "Assembly_Accession": "GCA_003028755.1",
    "Genbank_Accession": "CP028307",
    "Method": "SPAdes v. 3.10.1",
    "Location": "Pakistan: Sheikh Zaid Hospital, Lahore",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043352.2",
    "Additional_Metadata": "Asma Manzoor, Nabila Ishaq"
  },
  {
    "Strain": "SB-U321",
    "Host": "Homo sapiens",
    "Collection_date": "1/1/2025",
    "Length": 5107553,
    "N50": 39716,
    "Contigs": 371,
    "GC_Content": 51,
    "CDS": 5198,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary Tract Infection",
    "Level": "Contig",
    "Platform": "Illumina",
    "Genome_Coverage": "42x",
    "BioProject_Accession": "PRJNA1284627",
    "BioSample_Accession": "SAMN49729021",
    "Assembly_Accession": "GCA_051906035.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. v4.2.0",
    "Location": "Pakistan: Karachi",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Shaista Bhakhat, The Aga Khan University"
  },
  {
    "Strain": "SB-U322",
    "Host": "Homo sapiens",
    "Collection_date": "1/5/2025",
    "Length": 5076071,
    "N50": 45484,
    "Contigs": 343,
    "GC_Content": 51,
    "CDS": 5126,
    "MLST": "ST167",
    "Phylogroup": "A",
    "Serovar": "-:H9",
    "Host_disease": "Urinary Tract Infection",
    "Level": "Contig",
    "Platform": "Illumina",
    "Genome_Coverage": "39x",
    "BioProject_Accession": "PRJNA1284627",
    "BioSample_Accession": "SAMN49729022",
    "Assembly_Accession": "GCA_051906015.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. v4.2.0",
    "Location": "Pakistan: Karachi",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000139680.37",
    "Additional_Metadata": "Shaista Bhakhat, The Aga Khan University"
  },
  {
    "Strain": "U1",
    "Host": "Homo sapiens",
    "Collection_date": "12/18/2019",
    "Length": 5272959,
    "N50": 151471,
    "Contigs": 118,
    "GC_Content": 50.70853,
    "CDS": 5470,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina HiSeq",
    "Genome_Coverage": "98.02x",
    "BioProject_Accession": "PRJNA770824",
    "BioSample_Accession": "SAMN22237386",
    "Assembly_Accession": "",
    "Genbank_Accession": "JAJAWD000000000",
    "Method": "CLC Genomics Workbench v. 20.0.4",
    "Location": "Pakistan: Rawalpindi, Fauji Foundation Hospital",
    "Isolation_source": "UTI patients",
    "Isolation_type": "clinical",
    "SNP_cluster": "",
    "Additional_Metadata": "Zaara Ishaq"
  },
  {
    "Strain": "UPEC ECZMYU21",
    "Host": "Homo sapiens",
    "Collection_date": "12/3/2020",
    "Length": 5206704,
    "N50": 94224,
    "Contigs": 207,
    "GC_Content": 51,
    "CDS": 5186,
    "MLST": "_",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina",
    "Genome_Coverage": "79x",
    "BioProject_Accession": "PRJNA1073384",
    "BioSample_Accession": "SAMN39829063",
    "Assembly_Accession": "GCA_037483125.1",
    "Genbank_Accession": "",
    "Method": "SPAdes v. 3.9",
    "Location": "Pakistan",
    "Isolation_source": "Urine sample",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000156369.5",
    "Additional_Metadata": "AEG laboratory, department of Microbiology, Quaid-i-azam University, Islamabad"
  },
  {
    "Strain": "ZRUEC11",
    "Host": "Homo sapiens",
    "Collection_date": 2013,
    "Length": 5326642,
    "N50": 191062,
    "Contigs": 136,
    "GC_Content": 50.717358,
    "CDS": 5718,
    "MLST": "ST131",
    "Phylogroup": "B2",
    "Serovar": "O25:H4",
    "Host_disease": "Urinary Tract Infection",
    "Level": "Contig",
    "Platform": "Illumina HiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA473498",
    "BioSample_Accession": "SAMN09274370",
    "Assembly_Accession": "GCA_003668735.1",
    "Genbank_Accession": "QICE00000000",
    "Method": "SPAdes v. 4.11",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000226050.1",
    "Additional_Metadata": "Ihsan Ali"
  },
  {
    "Strain": "ZRUEC59",
    "Host": "Homo sapiens",
    "Collection_date": 2013,
    "Length": 5334668,
    "N50": 199986,
    "Contigs": 143,
    "GC_Content": 50.541027,
    "CDS": 5672,
    "MLST": "ST38",
    "Phylogroup": "D",
    "Serovar": "O1:H15",
    "Host_disease": "Urinary tract infection",
    "Level": "Contig",
    "Platform": "Illumina HiSeq",
    "Genome_Coverage": "30x",
    "BioProject_Accession": "PRJNA474355",
    "BioSample_Accession": "SAMN09298662",
    "Assembly_Accession": "GCA_004193385.1",
    "Genbank_Accession": "QKMW00000000",
    "Method": "SPAdes v. 4.11",
    "Location": "Pakistan",
    "Isolation_source": "urine",
    "Isolation_type": "clinical",
    "SNP_cluster": "PDS000043001.3",
    "Additional_Metadata": "Ihsan Ali"
  },
  {
    "Strain": "",
    "Host": "",
    "Collection_date": "",
    "Length": 5175979.959,
    "N50": "",
    "Contigs": "",
    "GC_Content": 50.637562,
    "CDS": 5180.506849,
    "MLST": "",
    "Phylogroup": "",
    "Serovar": "",
    "Host_disease": "",
    "Level": "",
    "Platform": "",
    "Genome_Coverage": "",
    "BioProject_Accession": "",
    "BioSample_Accession": "",
    "Assembly_Accession": "",
    "Genbank_Accession": "",
    "Method": "",
    "Location": "",
    "Isolation_source": "",
    "Isolation_type": "",
    "SNP_cluster": "",
    "Additional_Metadata": ""
  }
];
